name: Windows 10 Tailscale
 
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Updating Packages and Getting QEMU..
        run: |
          sudo apt update -y
          sudo apt install qemu-kvm cpulimit wget -y
          sudo wget -O bios64.bin "https://github.com/BlankOn/ovmf-blobs/raw/master/bios64.bin"
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Downloading Disk File And Setting Up Windows..
        run: |
          sudo chmod 666 /dev/kvm
          echo "Downloading Disk File.."
          sudo qemu-img create -f qcow2 /mnt/b.qcow2 100G
          wget -O a.qcow2 "https://qiwi.gg/file/d5kP7497-win" > /dev/null 2>&1
          echo "Disk is Downloaded, Now Moving.."
          sudo cp a.qcow2 /mnt
          echo "Disk Download and Move Has Completed, Driver File is Setting Up Now.."
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          wget -O driver.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso > /dev/null 2>&1
          echo "Everything is Set Up. Starting Windows Now.."
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          echo "Windows Started Successfully, Connection Credentials is Here!"
          echo "user: Administrator"
          echo "pass: 1"
          echo "VNC: 5900"
          echo "RDP: 23"
          tailscale ip -4
          sudo cpulimit -l 65 -- sudo kvm -M pc,usb=on -m 12G -smp 2,cores=2 -cpu host -drive file=driver.iso,media=cdrom -drive file=/mnt/a.qcow2,format=raw -drive file=/mnt/b.qcow2,format=raw -device usb-ehci,id=usb,bus=pci.0,addr=0x4 -device usb-tablet -vnc :0 -device virtio-balloon-pci -vga qxl -net nic,netdev=n0 -netdev user,id=n0,hostfwd=tcp::23-:3389 -boot c -enable-kvm -bios bios64.bin
          while ps axg | grep -vw grep | grep -w qemu-system-x86_64 > /dev/null; do sleep 1; done
          while ps axg | grep -vw grep | grep -w kvm > /dev/null; do sleep 1; done
