name: Windows 11 Canary Tail

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install qemu-kvm cpulimit wget -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo qemu-img create -f qcow2 /mnt/a.qcow2 60G
          sudo qemu-img create -f raw a.img 20G
          wget -O file.iso "https://software.download.prss.microsoft.com/dbazure/Windows11_InsiderPreview_Client_x64_en-us_26040.iso?t=1e90ffbf-8744-4a7f-a054-07ba2df2b321&P1=1707699097&P2=601&P3=2&P4=huw6X0BTqf3ZM4zG0VsEVTDFjUXOcQ5n7c2luAFkOXRfkZ%2bzYNznyJmXs3ChfE9pqjkO3mcyK5WWgpgjMfN0TWhfuQQ%2b4fio9ZnrfN1tUW1KeaLHKhJgZ7%2fDFtAQIBGLbzmR5pkSBC1S5fhMtGoaJTqU1DS1bk3yqseQpJfJf5pWi3fGGqWv7CbnS4A9fgI44GS3EbOL%2bj1M8MU727GIt2Nd9%2bOCKREzCsbGznrBG%2bfTPMCCddP4K5HsGSEMBpn7fOQxQY8MH5kq9j7im9icVaZT7MJFYkMauyzkt3I2WJRKBp4v7Wpyu4Ui1SPW%2fXS4p4PDUGQfrchieRKgIACgPw%3d%3d" &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          wget -O driver.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          echo "thanh cong, ket noi voi port 5900 bang vnc"
          tailscale ip -4
          sudo cpulimit -l 60 -- sudo kvm -M q35,usb=on -device usb-tablet -cpu host -smp 2 -m 8G -device virtio-balloon-pci -vga qxl -net nic,netdev=n0 -netdev user,id=n0 -boot c -device virtio-serial-pci -device virtio-rng-pci -enable-kvm -drive file=/mnt/a.qcow2 -drive file=file.iso,media=cdrom -drive file=a.img,format=raw,id=stick,if=none -device nec-usb-xhci,id=xhci -device usb-storage,bus=xhci.0,drive=stick -drive file=driver.iso,media=cdrom  -vnc :0 -bios /usr/share/ovmf/OVMF.fd -uuid e47ddb84-fb4d-46f9-b531-14bb15156336
          while ps axg | grep -vw grep | grep -w qemu-system-x86_64 > /dev/null; do sleep 1; done
          while ps axg | grep -vw grep | grep -w kvm > /dev/null; do sleep 1; done
